/**
 * This code can be used to generate an initial OpenAPI specification for the Blackboard 2.0 API.
 * Note: The file server/src/blackboard_openapi.json is hand-edited after the initial generation.
 */

const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'})

const outputFile = './blackboard_openapi_autogen.json'
const endpointsFiles = ['./server.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "Blackboard 2.0 API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    definitions: {
        PresentationProperties: {
            presenterpw: "v3rysecretpw",
            sessionname: "My first presentation",
            viewerpw: "",
            ispublic: true
        },
        PresentationSettings: {
            ui: {
                mouse: false, 
                complex: true,
                penOnly: false,
                showFps: false,
                showPps: false,
                showClock: true,
                showFSDialog: true,
                swipeEnabled: false,
                showViewerCount: true
            },
            line: {
                width: 0.15,
                bezier: true,
                allEvents: false,
                wipeWidth: 10,
                showPoints: false,
                lineTension: 0.3,
                distThreshold: 0.005,
                pointsThresholdMs: 16
            },
            laser: {
                size: 1,
                color: "#ff0000"
            },
            boards: {
                ab: 3,
                sb: 1,
                nvb: 4
            }
        },
        BoardSettings: {
            bg: {
                url: "https://server.mydomain.com/images/sample.png",
                visible: true
            },
            grid: {
                snap: false,
                aspect: 2.651697699890471,
                square: true,
                stroke: "#ffffff",
                opacity: 0.25,
                present: false,
                visible: false,
                cellWidth: 38,
                cellHeight: 20,
                strokeWidth: 0.04
            }
        },
        ShapeProperties: {
            shapeId: 123,
            $boardId: 3,
            visible: true,
            startTime: 1652453720284,
            shapeType: "Line",
            stroke: "#f5f5f5",
            fill: "#f5f5f5",
            x: 0.2522,
            y: 0.2457,
            strokeWidth: 0.15031,
            strokeEnabled: true,
            fillEnabled: false,
            bezier: true,
            tension: 0.3,
            closed: false,
            width: 0.342,
            height: 0.146,
            radius: 0.243,
            radiusX: 0.123,
            radiusY: 0.321,
            hspacing: 0.14,
            vspacing: 0.23,
            points: [[0,0,0],[27,0.00566,-0.00326],[47,0.0195,-0.01522]]
        },
        DeleteShapes: {
            $dbIds: [123,234,456],
            board: 3
        },
        CloneShape: {
            $shapeId: 123,
            $x: 0.346,
            $y: 0.789
        },
        ShapeRecolor: {
            dbIds: [123,234,345],
            color: "#f5f5f5"
        },
        BoardColors: {
            colors: [
                {
                    bgcolor: "#ffseff"
                },
                {
                    bgcolor: "#284646"
                }
            ]
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc)